import Link from "next/link";

import { StatusBadge } from "@/components/status-badge";
import { formatAttentionSeverity, formatDemoDate } from "@/domain/presentation";
import type { AttentionItem, Program } from "@/domain/types";

export function AttentionQueue({ items, programs, demoRequirementIsApproved, onConfirmRequirement, onResetDemo }: { items: AttentionItem[]; programs: Program[]; demoRequirementIsApproved: boolean; onConfirmRequirement: (requirementId: string) => void; onResetDemo: () => void }) {
  const programNames = new Map(programs.map((program) => [program.id, program.name]));
  return (
    <section className="border-t border-[var(--divider)]" aria-labelledby="attention-heading">
      <div className="flex items-start justify-between gap-4 border-b border-[var(--divider)] py-5"><div><p className="text-xs text-[var(--muted)]">Prioritised queue</p><h2 id="attention-heading" className="mt-1 text-xl font-semibold text-[var(--ink)]">Attention</h2><p className="mt-1 text-sm text-[var(--muted)]">Explainable rules, ordered by urgency and impact.</p></div><span className="text-xs font-semibold tabular-nums text-[var(--burgundy)]">{items.length} items</span></div>
      {demoRequirementIsApproved ? <div className="flex flex-col gap-3 border-b border-[var(--sage)] bg-[#f0f2ee] px-4 py-4 sm:flex-row sm:items-center sm:justify-between" role="status" aria-live="polite"><div><p className="text-sm font-semibold text-[var(--ink)]">Travel insurance · Approved</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Participant readiness, attention, and program metrics were recalculated.</p></div><button type="button" onClick={onResetDemo} className="inline-flex min-h-10 shrink-0 items-center justify-center rounded border border-[var(--sage)] bg-[var(--surface)] px-3 py-2 text-sm font-semibold text-[var(--navy)] hover:bg-white">Reset demo</button></div> : null}
      <div className="divide-y divide-[var(--divider)]">{items.map((item) => <article key={item.id} className="py-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><StatusBadge tone={item.severity}>{formatAttentionSeverity(item.severity)}</StatusBadge>{item.recommendedAction === "Confirm requirement" ? <span className="text-xs text-[var(--burgundy)]">Action required</span> : null}<span className="text-xs text-[var(--muted)]">Due {formatDemoDate(item.dueDate)}</span></div><h3 className="mt-3 font-semibold text-[var(--ink)]">{item.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{item.reason}</p><p className="mt-1 truncate text-xs text-[var(--muted)]">{programNames.get(item.programId)}</p></div>{item.recommendedAction === "Confirm requirement" ? <button type="button" onClick={() => onConfirmRequirement(item.sourceId)} className="inline-flex min-h-10 shrink-0 items-center justify-center rounded border border-[var(--divider)] bg-[var(--surface)] px-3 py-2 text-sm font-semibold text-[var(--navy)] hover:bg-white">{item.recommendedAction}</button> : <Link href={item.href} className="inline-flex min-h-10 shrink-0 items-center justify-center rounded border border-[var(--divider)] bg-[var(--surface)] px-3 py-2 text-sm font-semibold text-[var(--navy)] hover:bg-white">{item.recommendedAction}</Link>}</div></article>)}</div>
    </section>
  );
}
